In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.shape

(7043, 21)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df.drop("customerID", axis=1, inplace=True)

In [7]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

In [8]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
df["TotalCharges"] = df["TotalCharges"].fillna(
    df["TotalCharges"].median()
)

In [10]:
df["Churn"] = df["Churn"].map({
    "No":0,
    "Yes":1
})

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   int64
dtypes: float64(2), int64(3), object(15)
memory usage: 1.1+ MB

In [12]:
df["Charges_Per_Month"] = (
    df["TotalCharges"] /
    (df["tenure"] + 1)
)

df["Tenure_MonthlyCharges"] = (
    df["tenure"] *
    df["MonthlyCharges"]
)

In [13]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [14]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [15]:
X

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Charges_Per_Month,Tenure_MonthlyCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,14.925000,29.85,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,53.985714,1936.30,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,36.050000,107.70,True,False,False,True,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,40.016304,1903.50,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,50.550000,141.40,False,False,False,True,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,79.620000,2035.20,True,True,True,True,...,False,True,False,True,True,False,True,False,False,True
7039,0,72,103.20,7362.90,100.861644,7430.40,False,True,True,True,...,False,True,False,True,True,False,True,True,False,False
7040,0,11,29.60,346.45,28.870833,325.60,False,True,True,False,...,False,False,False,False,False,False,True,False,True,False
7041,1,4,74.40,306.60,61.320000,297.60,True,True,False,True,...,False,False,False,False,False,False,True,False,False,True
7042,0,66,105.65,6844.50,102.156716,6972.90,True,False,False,True,...,False,True,False,True,False,True,True,False,False,False

In [16]:
X.shape

(7043, 32)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5634, 32), (1409, 32), (5634,), (1409,))

In [18]:
import sys

print(sys.executable)

c:\AI Women Women workshop\myenv\Scripts\python.exe

In [19]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\ai women women workshop\myenv\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\ai women women workshop\myenv\lib\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in c:\ai women women workshop\myenv\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\ai women women workshop\myenv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\ai women women workshop\myenv\lib\site-packages (from scikit-learn) (3.6.0)

In [20]:
import sklearn
print(sklearn.__version__)

1.6.1

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
from sklearn.svm import SVC

In [24]:
svm_model = SVC(
    random_state=42
)

svm_model.fit(
    X_train_scaled,
    y_train
)

SVC(random_state=42)

In [25]:
svm_model.score(
    X_train_scaled,
    y_train
)

0.8166489172878949

In [26]:
svm_pred = svm_model.predict(
    X_test_scaled
)

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [28]:
precision_score(y_test, svm_pred), recall_score(y_test, svm_pred), f1_score(y_test, svm_pred)

(0.6818181818181818, 0.5227882037533512, 0.5918057663125948)

In [29]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_test, svm_pred))
print("Precision:", precision_score(y_test, svm_pred))
print("Recall   :", recall_score(y_test, svm_pred))
print("F1 Score :", f1_score(y_test, svm_pred))

Accuracy : 0.8090844570617459
Precision: 0.6818181818181818
Recall   : 0.5227882037533512
F1 Score : 0.5918057663125948

In [30]:
from sklearn.model_selection import GridSearchCV

svm_params = {
    "C":[0.1,1,10],
    "kernel":["linear","rbf"],
    "gamma":["scale","auto"]
}

In [31]:
svm_grid = GridSearchCV(
    SVC(),
    param_grid=svm_params,
    cv=5
)

svm_grid.fit(
    X_train_scaled,
    y_train
)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']})

In [32]:
svm_grid.best_params_

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}

In [33]:
svm_grid_pred = svm_grid.predict(
    X_test_scaled
)

print("Accuracy :", accuracy_score(y_test, svm_grid_pred))
print("Precision:", precision_score(y_test, svm_grid_pred))
print("Recall   :", recall_score(y_test, svm_grid_pred))
print("F1 Score :", f1_score(y_test, svm_grid_pred))

Accuracy : 0.815471965933286
Precision: 0.6996466431095406
Recall   : 0.5308310991957105
F1 Score : 0.6036585365853658